services:
    polifonic.mailer.base:
        class: Polifonic\Bunde\MailerBundle\Mailer\TwigSwiftMailer
        arguments:
            - "@mailer"
            - "@twig"

    polifonic.mailer.fos_user:
        class: Polifonic\Bunde\MailerBundle\Mailer\FOSUserTwigSwiftMailer
        arguments:
            - "@mailer"
            - "@router"
            - "@twig"
            -
                template:
                    confirmation: %fos_user.registration.confirmation.template%
                    resetting: %fos_user.resetting.email.template%
                from_email:
                    confirmation: %fos_user.registration.confirmation.from_email%
                    resetting: %fos_user.resetting.email.from_email%
